version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - app
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    networks:
      - app
    ports:
      - 8080:8080

networks:
  app: