version: '3.4'

services:
  postgres-test:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"